package(default_visibility = ["//websensus/java/com/websensus/reviews:internal"])

java_library(
    name = "options",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party:guice",
        "@com_google_guava_guava//jar",
        "@commons_cli//jar",
    ],
)
